// src/routes/youtube-feed-customizer/privacy-policy/+page.svelte
<h1 id="privacy-policy">Privacy Policy</h1>
<p
    >YouTube Feed Customizer is committed to protecting your privacy. This
    Privacy Policy explains how we collect, use, and safeguard your information
    when you use our Chrome extension.</p
>
<h3 id="information-collection-and-use">Information Collection and Use</h3>
<ol>
    <li
        ><p
            ><strong>Channel Preferences</strong>: We collect and store the
            names of YouTube channels you choose to include in your customized
            feed. This information is stored locally on your device and, if
            you&#39;re signed into Chrome, synced across your devices using
            Chrome&#39;s storage API.</p
        >
    </li>
    <li
        ><p
            ><strong>Usage Data</strong>: We do not collect any personal
            information, browsing history, or usage data beyond the channel
            names you explicitly provide.</p
        >
    </li>
</ol>
<h3 id="data-storage-and-security">Data Storage and Security</h3>
<ol>
    <li
        >All data is stored locally on your device using Chrome&#39;s secure
        storage API.</li
    >
    <li
        >If you&#39;re signed into Chrome, your channel list is synced across
        your devices using Chrome&#39;s secure sync functionality.</li
    >
    <li>We do not have access to this data, nor is it stored on our servers.</li
    >
</ol>
<h3 id="third-party-access">Third-Party Access</h3>
<ol>
    <li>We do not share, sell, or transfer your data to any third parties.</li>
    <li
        >Your data remains entirely under your control within the Chrome browser
        environment.</li
    >
</ol>
<h3 id="changes-to-youtube-com">Changes to YouTube.com</h3>
<ol>
    <li
        >Our extension modifies the appearance of YouTube.com on your device by
        hiding videos from channels not in your allowed list.</li
    >
    <li
        >These changes are made locally and do not affect YouTube&#39;s servers
        or other users&#39; experiences.</li
    >
</ol>
<h3 id="updates-and-changes">Updates and Changes</h3>
<p
    >We may update this Privacy Policy from time to time. We will notify you of
    any changes by posting the new Privacy Policy on the Chrome Web Store
    listing for YouTube Feed Customizer.</p
>
<h3 id="contact-us">Contact Us</h3>
<p
    >If you have any questions about this Privacy Policy, please contact us at
    chandyajin@gmail.com</p
>
<p
    >By using the YouTube Feed Customizer extension, you agree to the collection
    and use of information in accordance with this policy.</p
>
<p>Last updated: 02/08/24</p>

// app/projects/where-paste/privacy-policy/page.tsx
export default function PrivacyPolicy() {
  return (
    <div className="p-4">
      <h1 id="privacy-policy">Privacy Policy</h1>
      <p>
        <strong>Privacy Policy for WherePaste?</strong>
      </p>
      <p>
        <em>Last updated: [31-08-2024]</em>
      </p>
      <p>
        <strong>1. Introduction</strong>
        WherePaste? (&quot;the Extension&quot;) is committed to protecting your
        privacy. This Privacy Policy explains how we collect, use, and safeguard
        your information when you use our Chrome extension.
      </p>
      <p>
        <strong>2. Information We Collect</strong>
      </p>
      <ul>
        <li>
          <strong>Clipboard Data:</strong> The Extension temporarily reads and
          stores clipboard content to provide functionality such as clipboard
          history and smart link detection. This data is stored locally on your
          device and is never transmitted to any external servers.
        </li>
        <li>
          <strong>Storage Data:</strong> The Extension uses local storage to
          save your clipboard history. This data is only accessible by the
          Extension and is used solely for providing the features described.
        </li>
        <li>
          <strong>Tabs Interaction:</strong> The Extension may interact with
          your browser tabs to open URLs that you choose from your clipboard
          history. This interaction is limited to opening new tabs and does not
          involve accessing or modifying other tabs.
        </li>
      </ul>
      <p>
        <strong>3. How We Use Your Information</strong>
      </p>
      <ul>
        <li>
          <strong>Providing Services:</strong> The information collected is used
          to deliver the core features of the Extension, such as managing your
          clipboard history and opening links.
        </li>
        <li>
          <strong>Local Storage:</strong> All data is stored locally in your
          browser and is not shared with or accessible to any external parties.
        </li>
      </ul>
      <p>
        <strong>4. Data Security</strong>
      </p>
      <ul>
        <li>
          <strong>Local Storage:</strong> Clipboard history and related data are
          stored locally on your device, ensuring that no external parties can
          access your information.
        </li>
        <li>
          <strong>No External Transmission:</strong> The Extension does not
          transmit any data to external servers, providing enhanced security and
          privacy for users.
        </li>
      </ul>
      <p>
        <strong>5. User Control</strong>
      </p>
      <ul>
        <li>
          <strong>Clipboard Access:</strong> You can control when the Extension
          reads your clipboard by interacting with the extension&#39;s
          interface. The Extension does not monitor clipboard content in the
          background.
        </li>
        <li>
          <strong>Data Deletion:</strong> You can clear your clipboard history
          at any time through the Extension&#39;s interface.
        </li>
      </ul>
      <p>
        <strong>6. Changes to This Privacy Policy</strong>
        We may update this Privacy Policy from time to time. Any changes will be
        reflected in the updated policy, with the &quot;Last updated&quot; date
        at the top of this document.
      </p>
      <p>
        <strong>7. Contact Us</strong>
        If you have any questions or concerns about this Privacy Policy, please
        contact us at careerajin@gmail.com .
      </p>
      <hr />
      <p>
        These justifications and privacy policy should help clarify the purpose
        of the permissions and ensure users that their privacy is protected when
        using your Chrome extension.
      </p>
    </div>
  );
}
